version: '3.8'

volumes:
  nmdb-redis-data:
    driver: local

networks:
  nmdb-net:
    driver: bridge

services:
  neural-meduza-discord-broadcaster:
    image: neural-meduza-discord-broadcaster:latest
    container_name: neural-meduza-discord-broadcaster
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    networks:
      - nmdb-net
    restart: always

  neural-meduza-discord-broadcaster-redis:
    image: redis:latest
    container_name: neural-meduza-discord-broadcaster-redis
    expose:
      - 6379
    volumes:
      - nmdb-redis-data:/data
    networks:
      - nmdb-net
    restart: always